import {createClient} from '@supabase/supabase-js';
import {notFound} from 'next/navigation';
import ProjectLeadForm from '../../components/ProjectLeadForm';

const wa=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'918850373012';
function client(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)}
async function getProject(slug){const supabase=client();const{data:project}=await supabase.from('projects').select('*,developers(name,logo_url,description),locations(name,zone,description)').eq('slug',slug).eq('active',true).maybeSingle();if(!project)return null;const{data:inventory}=await supabase.from('inventory').select('id,configuration,carpet_area_sqft,carpet_area_max_sqft,price,availability,parking,last_verified').eq('project_id',project.id).eq('active',true).order('price',{ascending:true});return{project,inventory:inventory||[]}}
export async function generateMetadata({params}){const {slug}=await params;const result=await getProject(slug);if(!result)return{title:'Project Not Found | Way2Paisa'};const p=result.project;return{title:p.seo_title||`${p.name} | ${p.locations?.name||p.market||'Mumbai'} | Way2Paisa`,description:p.seo_description||p.description||`${p.name} by ${p.developers?.name||'leading developer'} — price, configuration, carpet area, possession and enquiry details from Way2Paisa.`}}
export default async function ProjectPage({params}){const{slug}=await params;const result=await getProject(slug);if(!result)notFound();const{project:p,inventory}=result;const msg=`Hi Way2Paisa, I am interested in ${p.name}${p.locations?.name?`, ${p.locations.name}`:''}. Please share latest price, inventory and site visit details.`;const price=p.price_original||formatPrice(p.min_price);return <main><Header/><section className="projectHero"><div className="projectHeroImage">{p.hero_image_url?<img src={p.hero_image_url} alt={p.name}/>:<div className="projectFallback"><img src="/way2paisa-mark.jpg" alt=""/><span>WAY2PAISA SELECT</span></div>}<div className="projectOverlay"></div><div className="projectHeroContent"><a className="breadcrumb" href="/properties">← All Properties</a><span className="projectLocation">{p.locations?.name||p.market||'Mumbai'} · {p.developers?.name||'Leading Developer'}</span><h1>{p.name}</h1><div className="projectPills">{p.bhk_original&&<span>{p.bhk_original}</span>}{p.carpet_area_original&&<span>{p.carpet_area_original} sq.ft.</span>}{p.status&&<span>{p.status}</span>}</div></div></div></section>
<section className="projectSummary"><div><span>Starting Price</span><strong>{price||'On Request'}</strong></div><div><span>Configuration</span><strong>{p.bhk_original||'Contact Us'}</strong></div><div><span>Carpet Area</span><strong>{p.carpet_area_original?`${p.carpet_area_original} sq.ft.`:areaRange(p)}</strong></div><div><span>Possession</span><strong>{p.possession_original||p.possession_date||'Contact Us'}</strong></div></section>
<section className="projectContent"><div className="projectMain"><div className="contentBlock"><span className="kicker">PROJECT OVERVIEW</span><h2>About {p.name}</h2><p>{p.description||`${p.name} is a residential opportunity by ${p.developers?.name||'a leading developer'} in ${p.locations?.name||p.market||'Mumbai'}. Connect with Way2Paisa for current inventory, developer offers, pricing and a curated site visit.`}</p></div>
<div className="contentBlock"><span className="kicker">PROJECT DETAILS</span><h2>At a glance</h2><div className="detailGrid"><Detail label="Developer" value={p.developers?.name}/><Detail label="Location" value={p.locations?.name||p.market}/><Detail label="Status" value={p.status}/><Detail label="RERA" value={p.rera_number||'Available on request'}/><Detail label="Carpet Area" value={p.carpet_area_original?`${p.carpet_area_original} sq.ft.`:areaRange(p)}/><Detail label="Possession" value={p.possession_original||p.possession_date}/></div></div>
<div className="contentBlock"><span className="kicker">AVAILABLE CONFIGURATIONS</span><h2>Inventory snapshot</h2>{inventory.length?<div className="inventoryTable"><div className="inventoryHead"><span>Configuration</span><span>Carpet Area</span><span>Price</span><span>Availability</span></div>{inventory.map(x=><div className="inventoryRow" key={x.id}><strong>{x.configuration||'Residence'}</strong><span>{area(x)}</span><span>{formatPrice(x.price)}</span><span>{x.availability||'Enquire'}</span></div>)}</div>:<div className="inventoryEmpty">Current inventory is available through our advisory team. Request the latest price sheet and unit availability.</div>}</div>
<div className="contentBlock locationBlock"><span className="kicker">LOCATION</span><h2>{p.locations?.name||p.market||'Mumbai'}</h2><p>{p.locations?.description||p.address||`Well connected to key business, lifestyle and social infrastructure across ${p.market||'Mumbai Metropolitan Region'}.`}</p></div></div>
<aside className="projectSidebar"><div className="stickyCard"><ProjectLeadForm project={{id:p.id,name:p.name}}/><a className="projectWa" href={`https://wa.me/${wa}?text=${encodeURIComponent(msg)}`} target="_blank">WhatsApp an Advisor</a><div className="advisorNote"><b>Way2Paisa Advantage</b><span>Priority inventory access</span><span>Developer-direct coordination</span><span>Home-loan assistance</span><span>Zero brokerage to buyers</span></div></div></aside></section>
<section className="projectCta"><div><span className="kicker light">PERSONALISED ADVISORY</span><h2>Considering {p.name}?</h2><p>We'll help you compare the right configuration, current inventory and competing projects before you decide.</p></div><a href={`https://wa.me/${wa}?text=${encodeURIComponent(msg)}`} target="_blank">Speak to Way2Paisa</a></section><Footer/></main>}
function Header(){return <header className="nav"><a className="logoLink" href="/"><img src="/way2paisa-logo.png" alt="Way2Paisa FinPro Services"/></a><nav><a href="/properties">Properties</a><a href="/#locations">Locations</a><a href="/#advisory">Advisory</a><a href="/#about">About</a><a className="navCta" href="/#enquire">Speak to an Advisor</a></nav></header>}
function Detail({label,value}){return <div><span>{label}</span><strong>{value||'Available on request'}</strong></div>}
function formatPrice(v){if(v===null||v===undefined||v==='')return'Price on request';const n=Number(v);return Number.isFinite(n)?`₹${n.toLocaleString('en-IN',{maximumFractionDigits:2})} Cr`:'Price on request'}
function area(x){if(!x.carpet_area_sqft)return'On request';if(x.carpet_area_max_sqft&&Number(x.carpet_area_max_sqft)!==Number(x.carpet_area_sqft))return `${x.carpet_area_sqft}–${x.carpet_area_max_sqft} sq.ft.`;return `${x.carpet_area_sqft} sq.ft.`}
function areaRange(p){if(!p.min_carpet_sqft)return'On request';return p.max_carpet_sqft&&Number(p.max_carpet_sqft)!==Number(p.min_carpet_sqft)?`${p.min_carpet_sqft}–${p.max_carpet_sqft} sq.ft.`:`${p.min_carpet_sqft} sq.ft.`}
function Footer(){return <footer><div className="footerBrand"><img src="/way2paisa-logo.png" alt="Way2Paisa FinPro Services"/><p>Preferred Channel Partner for leading Developers, Banks & NBFC's.</p></div><div className="footerLinks"><a href="/properties">Properties</a><a href="/#locations">Locations</a><a href="/#enquire">Contact</a></div><div className="footerContact"><a href={`https://wa.me/${wa}`} target="_blank">+91 88503 73012</a><a href="mailto:way2paisaindia@gmail.com">way2paisaindia@gmail.com</a></div><div className="footerBottom">© {new Date().getFullYear()} Way2Paisa FinPro Services. All rights reserved.</div></footer>}
