'use client';

import {useState} from 'react';

const wa=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'918850373012';

export default function QuickContact(){
 const[open,setOpen]=useState(false),[form,setForm]=useState({name:'',phone:'',email:''}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const change=e=>setForm(current=>({...current,[e.target.name]:e.target.value}));
 async function submit(event){event.preventDefault();setBusy(true);setNotice('');try{const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,projectName:'Quick advisory enquiry',source:'Website - Sticky Enquiry Widget',landingPage:window.location.href})});const data=await response.json();if(!response.ok)throw new Error(data.error||'We could not send your request.');setNotice('Thank you. A Way2Paisa advisor will contact you shortly.');setForm({name:'',phone:'',email:''})}catch(error){setNotice(error.message||'We could not send your request.')}finally{setBusy(false)}}
 return <><div className="quickContact" aria-label="Contact Way2Paisa"><a className="quickWhatsApp" href={`https://wa.me/${wa}?text=${encodeURIComponent('Hi Way2Paisa, I would like property and finance advisory.')}`} target="_blank" rel="noopener noreferrer" aria-label="Chat with Way2Paisa on WhatsApp"><span aria-hidden="true">◔</span><b>WhatsApp</b></a><button className="quickEnquiry" type="button" onClick={()=>{setNotice('');setOpen(true)}}><span aria-hidden="true">✦</span><b>Enquire</b></button></div>{open&&<div className="quickDialogBackdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="quickDialog" role="dialog" aria-modal="true" aria-labelledby="quick-contact-title" onMouseDown={event=>event.stopPropagation()}><button className="quickClose" type="button" onClick={()=>setOpen(false)} aria-label="Close enquiry form">×</button><span className="kicker">WAY2PAISA ADVISORY</span><h2 id="quick-contact-title">Let’s find the right next step.</h2><p>Share your details and an advisor will call you for property or finance assistance.</p><form onSubmit={submit}><label>Name<input required name="name" value={form.name} onChange={change} placeholder="Your name"/></label><label>Mobile number<input required name="phone" inputMode="tel" value={form.phone} onChange={change} placeholder="Your mobile number"/></label><label>Email <em>(optional)</em><input name="email" type="email" value={form.email} onChange={change} placeholder="you@example.com"/></label><button className="primaryBtn" disabled={busy}>{busy?'Sending…':'Request a callback'}</button>{notice&&<p className="quickNotice" role="status">{notice}</p>}</form><small>By submitting, you authorise Way2Paisa to contact you about relevant real-estate and finance services.</small></section></div>}</>;
}
