'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const wa=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'918850373012';
const waLink=p=>`https://wa.me/${wa}?text=${encodeURIComponent(`Hi Way2Paisa, I am interested in ${p.name}${p.locations?.name?`, ${p.locations.name}`:''}. Please share details.`)}`;

export default function Home(){
 const[projects,setProjects]=useState([]),[locations,setLocations]=useState([]),[developers,setDevelopers]=useState([]),[q,setQ]=useState(''),[location,setLocation]=useState(''),[bhk,setBhk]=useState(''),[maxBudget,setMaxBudget]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const[{data:p,error:pe},{data:l},{data:d}]=await Promise.all([
  supabase.from('projects').select('id,name,slug,address,description,rera_number,possession_date,status,min_price,max_price,min_carpet_sqft,max_carpet_sqft,featured,verified,hero_image_url,market,bhk_original,carpet_area_original,price_original,possession_original,developer_id,location_id,developers(name,logo_url),locations(name,zone)').eq('active',true).order('featured',{ascending:false}).order('updated_at',{ascending:false}).limit(500),
  supabase.from('locations').select('id,name,zone').eq('active',true).order('name'),
  supabase.from('developers').select('id,name').eq('active',true).order('name')
 ]);if(pe)setError(pe.message);setProjects(p||[]);setLocations(l||[]);setDevelopers(d||[]);setLoading(false)})()},[]);
 const filtered=useMemo(()=>{const t=q.trim().toLowerCase();return projects.filter(p=>{const text=[p.name,p.address,p.market,p.bhk_original,p.developers?.name,p.locations?.name].filter(Boolean).join(' ').toLowerCase();return(!t||text.includes(t))&&(!bhk||(p.bhk_original||'').toLowerCase().includes(bhk.toLowerCase()))&&(!location||p.location_id===location)&&(!maxBudget||!p.min_price||Number(p.min_price)<=Number(maxBudget))})},[projects,q,bhk,location,maxBudget]);
 const propertyUrl=()=>{const sp=new URLSearchParams();if(q)sp.set('q',q);if(location)sp.set('location',location);if(bhk)sp.set('bhk',bhk);if(maxBudget)sp.set('budget',maxBudget);return `/properties${sp.toString()?`?${sp}`:''}`};
 return <main>
  <header className="nav">
   <a className="logoLink" href="/" aria-label="Way2Paisa FinPro Services"><img src="/way2paisa-logo.png" alt="Way2Paisa FinPro Services"/></a>
   <nav><a href="/properties">Properties</a><a href="#locations">Locations</a><a href="#advisory">Advisory</a><a href="#about">About</a><a className="navCta" href="#enquire">Speak to an Advisor</a></nav>
  </header>

  <section className="hero" id="top"><div className="heroGlow"></div><div className="heroInner">
   <div className="heroCopy"><div className="eyebrow">Mumbai · Navi Mumbai · Thane</div><h1>Find your next address.<br/><span>Invest with confidence.</span></h1><p>Curated residences, new launches and expert advisory from a preferred channel partner — with priority access, transparent guidance and zero brokerage.</p><div className="heroButtons"><a className="primaryBtn" href="/properties">Explore Projects</a><a className="secondaryBtn" href="#enquire">Get Expert Advice</a></div></div>
   <div className="heroPanel"><div className="panelLabel">PROPERTY DISCOVERY</div><div className="searchBox"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Project, developer or location"/><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">All locations</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select value={bhk} onChange={e=>setBhk(e.target.value)}><option value="">Any configuration</option>{['1 BHK','2 BHK','3 BHK','4 BHK','5 BHK'].map(x=><option key={x}>{x}</option>)}</select><select value={maxBudget} onChange={e=>setMaxBudget(e.target.value)}><option value="">Any budget</option><option value="2">Up to ₹2 Cr</option><option value="3">Up to ₹3 Cr</option><option value="5">Up to ₹5 Cr</option><option value="7.5">Up to ₹7.5 Cr</option><option value="10">Up to ₹10 Cr</option></select><a className="searchBtn" href={propertyUrl()}>Search Properties</a></div><div className="trustRow"><span>Verified opportunities</span><span>Developer-direct access</span><span>Dedicated advisory</span></div></div>
  </div></section>

  <section className="stats"><div><strong>{projects.length||206}+</strong><span>Projects</span></div><div><strong>440+</strong><span>Inventory Options</span></div><div><strong>{developers.length||41}+</strong><span>Developer Relationships</span></div><div><strong>0%</strong><span>Brokerage to Buyers</span></div></section>

  <section className="section" id="properties"><div className="sectionHead"><div><span className="kicker">CURATED RESIDENCES</span><h2>Featured opportunities</h2><p>Handpicked homes and investment opportunities across Mumbai's most sought-after micro-markets.</p></div><a className="count" href="/properties">View all {projects.length||206}+ projects →</a></div>{loading?<div className="loading">Loading live property database…</div>:error?<div className="error">Unable to load properties: {error}</div>:<div className="grid">{filtered.slice(0,12).map(p=><PropertyCard key={p.id} p={p}/>)}</div>}{!loading&&!error&&!filtered.length&&<div className="empty">No matching properties found. Try a wider search.</div>}</section>

  <section className="locations" id="locations"><div className="sectionHead"><div><span className="kicker">PRIME MICRO-MARKETS</span><h2>Explore by location</h2><p>Discover projects across established neighbourhoods and fast-growing residential corridors.</p></div></div><div className="locationGrid">{locations.slice(0,8).map((l,i)=><a key={l.id} href={`/properties?location=${l.id}`}><span className="locationNumber">0{i+1}</span><strong>{l.name}</strong><span>{l.zone||'Mumbai Metropolitan Region'}</span><b>View projects →</b></a>)}</div></section>

  <section className="advisory" id="advisory"><div className="advisoryCard"><div><span className="kicker light">WAY2PAISA ADVANTAGE</span><h2>More than listings.<br/>A smarter buying experience.</h2></div><div className="advantageGrid"><article><strong>01</strong><h3>Curated Shortlisting</h3><p>Recommendations aligned to your location, lifestyle, budget and investment goals.</p></article><article><strong>02</strong><h3>Priority Access</h3><p>Direct coordination with developer teams for inventory, launches and site visits.</p></article><article><strong>03</strong><h3>Finance Support</h3><p>Home-loan assistance through leading banks and NBFC relationships.</p></article><article><strong>04</strong><h3>End-to-End Guidance</h3><p>From first shortlist to negotiation, documentation and possession support.</p></article></div></div></section>

  <section className="leadSection" id="enquire"><div className="leadCopy"><span className="kicker">PRIVATE CONSULTATION</span><h2>Tell us what you're looking for.</h2><p>Share your preferred location, configuration and budget. Our advisory team will curate a relevant shortlist instead of overwhelming you with generic options.</p><div className="directContact"><span>Prefer WhatsApp?</span><a href={`https://wa.me/${wa}`} target="_blank">+91 88503 73012 →</a></div></div><LeadForm/></section>

  <section className="about" id="about"><div><span className="kicker">WAY2PAISA FINPRO SERVICES</span><h2>Finance and real estate expertise, under one roof.</h2></div><div><p>Way2Paisa combines property advisory with finance expertise to help clients make better-informed real-estate decisions across Mumbai and MMR.</p><div className="aboutTags"><span>Residential Properties</span><span>Home Loans</span><span>Property Advisory</span><span>Redevelopment Consultancy</span><span>Property Management</span><span>Interiors Assistance</span></div></div></section>

  <Footer/>
 </main>
}

function PropertyCard({p}){return <article className="card"><a className="imageWrap" href={`/projects/${p.slug}`}>{p.hero_image_url?<img src={p.hero_image_url} alt={p.name}/>:<div className="imageFallback"><div className="brandOrb">↗</div><span>WAY2PAISA SELECT</span><b>{p.locations?.name||p.market||'MUMBAI'}</b></div>}{(p.featured||p.verified)&&<span className="badge">{p.featured?'Featured':'Verified'}</span>}</a><div className="cardBody"><div className="muted">{p.developers?.name||'Leading Developer'} · {p.locations?.name||p.market||'Mumbai'}</div><h3><a href={`/projects/${p.slug}`}>{p.name}</a></h3><div className="facts">{p.bhk_original&&<span>{p.bhk_original}</span>}{p.carpet_area_original&&<span>{p.carpet_area_original} sq.ft.</span>}{p.status&&<span>{p.status}</span>}</div><div className="priceLine"><span>Starting</span><strong>{p.price_original||'Price on request'}</strong></div><div className="actions"><a className="detailsBtn" href={`/projects/${p.slug}`}>View Project</a><a className="waBtn" href={waLink(p)} target="_blank">WhatsApp</a></div></div></article>}

function LeadForm(){const[form,setForm]=useState({name:'',phone:'',email:'',preferred_bhk:'',budget:'',preferred_locations:''}),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function submit(e){e.preventDefault();setBusy(true);setErr('');const{error}=await supabase.from('leads').insert({...form,source:'Website',landing_page:window.location.href});if(error){setErr(error.message);setBusy(false);return}setSent(true);setBusy(false)}if(sent)return <div className="success"><strong>Thank you.</strong><p>Our advisory team will contact you shortly.</p><a href={`https://wa.me/${wa}`} target="_blank">Continue on WhatsApp</a></div>;return <form className="leadForm" onSubmit={submit}><Field label="Name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Mobile"><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Preferred Configuration"><select value={form.preferred_bhk} onChange={e=>setForm({...form,preferred_bhk:e.target.value})}><option value="">Select</option>{['1 BHK','2 BHK','3 BHK','4 BHK','5 BHK+'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Budget"><input placeholder="e.g. ₹5–7 Cr" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></Field><Field label="Preferred Locations"><input placeholder="e.g. Bandra, Juhu, Andheri West" value={form.preferred_locations} onChange={e=>setForm({...form,preferred_locations:e.target.value})}/></Field>{err&&<div className="formError">{err}</div>}<button disabled={busy}>{busy?'Submitting…':'Request a Curated Shortlist'}</button></form>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Footer(){return <footer><div className="footerBrand"><img src="/way2paisa-logo.png" alt="Way2Paisa FinPro Services"/><p>Preferred Channel Partner for leading Developers, Banks & NBFC's.</p></div><div className="footerLinks"><a href="/properties">Properties</a><a href="/#locations">Locations</a><a href="/#enquire">Contact</a></div><div className="footerContact"><a href={`https://wa.me/${wa}`} target="_blank">+91 88503 73012</a><a href="mailto:way2paisaindia@gmail.com">way2paisaindia@gmail.com</a></div><div className="footerBottom">© {new Date().getFullYear()} Way2Paisa FinPro Services. All rights reserved.</div></footer>}
