'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const platforms=['Instagram','Facebook','LinkedIn','X','YouTube'];

export default function PromotionStudio(){
 const [ready,setReady]=useState(false),[allowed,setAllowed]=useState(false),[projects,setProjects]=useState([]),[history,setHistory]=useState([]),[projectId,setProjectId]=useState(''),[caption,setCaption]=useState(''),[headline,setHeadline]=useState(''),[brief,setBrief]=useState(''),[selected,setSelected]=useState(['Instagram','Facebook']),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){setReady(true);return}const {data:profile}=await db.from('admin_profiles').select('id').eq('id',user.id).eq('active',true).maybeSingle();if(!profile){setReady(true);return}setAllowed(true);const [{data:p},{data:h}]=await Promise.all([db.from('projects').select('id,name,slug,price_original,bhk_original,possession_original,rera_number,locations(name)').eq('active',true).eq('verified',true).order('name'),db.from('project_promotions').select('id,caption,platforms,status,created_at,projects(name)').order('created_at',{ascending:false}).limit(30)]);setProjects(p||[]);setHistory(h||[]);setReady(true)})()},[]);
 const project=useMemo(()=>projects.find(x=>x.id===projectId),[projects,projectId]);
 function createDraft(){if(!project)return;const lines=[project.name,project.locations?.name,project.bhk_original,project.price_original||'Price on Request',project.possession_original&&project.possession_original.replace('|',' · '),project.rera_number&&'MahaRERA: '+project.rera_number].filter(Boolean);setHeadline(project.name+' | '+(project.locations?.name||''));setCaption('Discover '+lines.join(' · ')+'. Connect with Way2Paisa for verified details and a personalised site visit.');setBrief('Create approved brand-led assets from verified project imagery only: square post, vertical Story/Reel, LinkedIn and X layouts. Include Way2Paisa logo, contact number, MahaRERA details and standard disclaimer. Do not use third-party portal branding or imagery.');}
 async function save(status){if(!project||!caption.trim()){setNotice('Choose a project and generate or enter the caption first.');return}setSaving(true);setNotice('');const {data:{user}}=await db.auth.getUser();const row={project_id:project.id,caption,headline,creative_brief:brief,platforms:selected,status,approved_by:status==='approved'?user?.id:null,approved_at:status==='approved'?new Date().toISOString():null};const {data,error}=await db.from('project_promotions').insert(row).select('id,caption,platforms,status,created_at,projects(name)').single();if(error)setNotice(error.message);else{setHistory(x=>[data,...x]);setNotice(status==='approved'?'Approved for connected-platform publishing.':'Promotion draft saved.');}setSaving(false)}
 if(!ready)return <main className="adminStudio"><p>Loading secure Promotion Studio…</p></main>;
 if(!allowed)return <main className="adminStudio"><h1>Admin access required</h1><p>Sign in with an active Way2Paisa admin account to create or review promotions.</p></main>;
 return <main className="adminStudio"><header><span>WAY2PAISA ADMIN</span><h1>AI Promotion Studio</h1><p>Create, edit and approve campaign drafts from verified project facts. Direct social publishing remains disabled until Way2Paisa platform credentials are connected.</p></header><section className="studioCard"><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select a verified project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button onClick={createDraft} disabled={!project}>Create promotion</button><label>Headline<input value={headline} onChange={e=>setHeadline(e.target.value)}/></label><label>Caption<textarea value={caption} onChange={e=>setCaption(e.target.value)} rows="6"/></label><label>Creative brief<textarea value={brief} onChange={e=>setBrief(e.target.value)} rows="5"/></label><fieldset><legend>Channels</legend>{platforms.map(x=><label key={x}><input type="checkbox" checked={selected.includes(x)} onChange={()=>setSelected(s=>s.includes(x)?s.filter(y=>y!==x):[...s,x])}/>{x}</label>)}</fieldset><div className="studioActions"><button onClick={()=>save('draft')} disabled={saving}>Save draft</button><button className="approveBtn" onClick={()=>save('approved')} disabled={saving}>Approve promotion</button></div>{notice&&<p className="studioNotice">{notice}</p>}</section><section><h2>Promotion history</h2>{history.length?<div className="history">{history.map(x=><article key={x.id}><b>{x.projects?.name||'Project'}</b><span>{x.status} · {x.platforms.join(', ')}</span><p>{x.caption}</p><small>{new Date(x.created_at).toLocaleString()}</small></article>)}</div>:<p>No promotion drafts yet.</p>}</section></main>;
}